export type LicenseCategory = 'Software' | 'Izin Usaha & Legalitas' | 'Sertifikasi Profesi';
export type LicenseStatus = 'Aktif' | 'Akan Kadaluarsa' | 'Kadaluarsa' | 'Non-aktif';

export interface License {
  id: string;
  name: string;
  category: LicenseCategory;
  licenseNumber: string;
  owner: string;
  vendor: string;
  issueDate: string;
  expiryDate: string;
  status: LicenseStatus;
  notes: string;
  fileUrl?: string;
  fileName?: string;
}

export const mockLicenses: License[] = [
  {
    id: '1',
    name: 'Microsoft 365 Business Premium',
    category: 'Software',
    licenseNumber: 'MS365-BP-2024-001',
    owner: 'Divisi IT',
    vendor: 'Microsoft Corporation',
    issueDate: '2025-01-15',
    expiryDate: '2026-01-15',
    status: 'Aktif',
    notes: 'Lisensi untuk 50 user. Mencakup Office Apps, Teams, dan OneDrive.',
    fileUrl: '#',
    fileName: 'MS365_License_2025.pdf',
  },
  {
    id: '2',
    name: 'Adobe Creative Cloud Enterprise',
    category: 'Software',
    licenseNumber: 'ADOBE-CC-ENT-2024-045',
    owner: 'Divisi Marketing',
    vendor: 'Adobe Inc.',
    issueDate: '2025-03-01',
    expiryDate: '2026-07-20',
    status: 'Akan Kadaluarsa',
    notes: '10 seat license. Photoshop, Illustrator, Premiere Pro.',
    fileUrl: '#',
    fileName: 'Adobe_CC_Agreement.pdf',
  },
  {
    id: '3',
    name: 'Nomor Induk Berusaha (NIB)',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'NIB-9120412340001',
    owner: 'Divisi Legal',
    vendor: 'OSS Kementerian Investasi',
    issueDate: '2023-06-10',
    expiryDate: '2028-06-10',
    status: 'Aktif',
    notes: 'NIB berlaku selama perusahaan beroperasi. Wajib update data berkala.',
    fileUrl: '#',
    fileName: 'NIB_Certificate.pdf',
  },
  {
    id: '4',
    name: 'Surat Izin Usaha Perdagangan (SIUP)',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'SIUP-503/11.74/PK/X/2022',
    owner: 'Divisi Legal',
    vendor: 'Dinas Penanaman Modal DKI Jakarta',
    issueDate: '2022-10-20',
    expiryDate: '2026-07-10',
    status: 'Akan Kadaluarsa',
    notes: 'SIUP Menengah. Perlu perpanjangan segera.',
    fileUrl: '#',
    fileName: 'SIUP_2022.pdf',
  },
  {
    id: '5',
    name: 'Sertifikasi PMP - Budi Santoso',
    category: 'Sertifikasi Profesi',
    licenseNumber: 'PMP-2847561',
    owner: 'Budi Santoso - Divisi PMO',
    vendor: 'Project Management Institute (PMI)',
    issueDate: '2024-02-14',
    expiryDate: '2027-02-14',
    status: 'Aktif',
    notes: 'Sertifikasi Project Management Professional. Perlu 60 PDU untuk renewal.',
    fileUrl: '#',
    fileName: 'PMP_BudiSantoso.pdf',
  },
  {
    id: '6',
    name: 'Sertifikasi ISO 27001 Lead Auditor - Rina Wati',
    category: 'Sertifikasi Profesi',
    licenseNumber: 'ISO27001-LA-ID-2023-188',
    owner: 'Rina Wati - Divisi IT Security',
    vendor: 'IRCA / BSI Group',
    issueDate: '2023-08-01',
    expiryDate: '2026-08-01',
    status: 'Aktif',
    notes: 'Lead Auditor ISO 27001:2022. Berlaku 3 tahun.',
    fileUrl: '#',
    fileName: 'ISO27001_LA_RinaWati.pdf',
  },
  {
    id: '7',
    name: 'Slack Business+ Subscription',
    category: 'Software',
    licenseNumber: 'SLK-BIZ-2024-077',
    owner: 'Divisi IT',
    vendor: 'Salesforce (Slack)',
    issueDate: '2025-04-01',
    expiryDate: '2026-04-01',
    status: 'Aktif',
    notes: 'Langganan tahunan untuk 200 user.',
    fileUrl: '#',
    fileName: 'Slack_Invoice_2025.pdf',
  },
  {
    id: '8',
    name: 'Izin Mendirikan Bangunan (IMB) Gedung Kantor',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'IMB-01/1.784.51/2019',
    owner: 'Divisi GA',
    vendor: 'Dinas CIPTA KARYA DKI Jakarta',
    issueDate: '2019-03-15',
    expiryDate: '2029-03-15',
    status: 'Aktif',
    notes: 'IMB untuk gedung kantor pusat 5 lantai. Berlaku permanen selama bangunan berdiri.',
  },
  {
    id: '9',
    name: 'AutoCAD LT - Single License',
    category: 'Software',
    licenseNumber: 'ACAD-LT-2024-032',
    owner: 'Divisi Engineering',
    vendor: 'Autodesk Inc.',
    issueDate: '2024-11-01',
    expiryDate: '2025-11-01',
    status: 'Kadaluarsa',
    notes: 'Lisensi sudah expired. Perlu evaluasi apakah akan diperpanjang.',
  },
  {
    id: '10',
    name: 'Sertifikasi AWS Solutions Architect - Dian P.',
    category: 'Sertifikasi Profesi',
    licenseNumber: 'AWS-SAA-C03-2024-5512',
    owner: 'Dian Permata - Divisi IT',
    vendor: 'Amazon Web Services',
    issueDate: '2024-05-20',
    expiryDate: '2027-05-20',
    status: 'Aktif',
    notes: 'AWS Certified Solutions Architect - Associate. Berlaku 3 tahun.',
    fileUrl: '#',
    fileName: 'AWS_SAA_DianPermata.pdf',
  },
  {
    id: '11',
    name: 'Tanda Daftar Perusahaan (TDP)',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'TDP-09.05.1.46.12345',
    owner: 'Divisi Legal',
    vendor: 'Dinas Perindustrian dan Perdagangan',
    issueDate: '2021-07-01',
    expiryDate: '2026-07-01',
    status: 'Kadaluarsa',
    notes: 'TDP sudah expired per 1 Juli 2026. Segera perpanjang!',
  },
  {
    id: '12',
    name: 'Jira Software Cloud Premium',
    category: 'Software',
    licenseNumber: 'JIRA-PREM-2025-019',
    owner: 'Divisi IT',
    vendor: 'Atlassian',
    issueDate: '2025-06-01',
    expiryDate: '2026-06-01',
    status: 'Aktif',
    notes: 'Premium plan untuk 100 user. Termasuk Advanced Roadmaps.',
    fileUrl: '#',
    fileName: 'Jira_Premium_Invoice.pdf',
  },
  {
    id: '13',
    name: 'Lisensi Kaspersky Endpoint Security',
    category: 'Software',
    licenseNumber: 'KAS-EP-2025-883',
    owner: 'Divisi IT Security',
    vendor: 'Kaspersky Lab',
    issueDate: '2025-02-10',
    expiryDate: '2026-02-10',
    status: 'Aktif',
    notes: 'Antivirus dan endpoint protection untuk 150 perangkat.',
    fileUrl: '#',
    fileName: 'Kaspersky_License.pdf',
  },
  {
    id: '14',
    name: 'Sertifikasi CEH - Ahmad Ridwan',
    category: 'Sertifikasi Profesi',
    licenseNumber: 'ECC-CEH-391002',
    owner: 'Ahmad Ridwan - Divisi IT Security',
    vendor: 'EC-Council',
    issueDate: '2023-10-15',
    expiryDate: '2026-10-15',
    status: 'Aktif',
    notes: 'Certified Ethical Hacker v12.',
  },
  {
    id: '15',
    name: 'Surat Izin Tempat Usaha (SITU)',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'SITU-503/44/2021',
    owner: 'Divisi GA',
    vendor: 'Pemerintah Daerah',
    issueDate: '2021-08-01',
    expiryDate: '2026-08-01',
    status: 'Akan Kadaluarsa',
    notes: 'SITU Kantor Cabang Bandung. Perlu diurus perpanjangannya bulan depan.',
  },
  {
    id: '16',
    name: 'Sertifikat Laik Fungsi (SLF) Gedung',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'SLF-002/11/2020',
    owner: 'Divisi GA',
    vendor: 'Dinas Penanaman Modal',
    issueDate: '2020-11-20',
    expiryDate: '2025-11-20',
    status: 'Kadaluarsa',
    notes: 'Masa berlaku SLF habis, sedang dalam proses perpanjangan dengan konsultan.',
  },
  {
    id: '17',
    name: 'Zoom Workplace Pro',
    category: 'Software',
    licenseNumber: 'ZM-PRO-2025-412',
    owner: 'Divisi IT',
    vendor: 'Zoom Video Communications',
    issueDate: '2025-01-05',
    expiryDate: '2026-01-05',
    status: 'Aktif',
    notes: '20 Host License untuk keperluan meeting online.',
  },
  {
    id: '18',
    name: 'Lisensi Cpanel/WHM',
    category: 'Software',
    licenseNumber: 'CP-PREM-1120',
    owner: 'Divisi IT Infrastructure',
    vendor: 'cPanel, L.L.C.',
    issueDate: '2025-04-12',
    expiryDate: '2026-04-12',
    status: 'Aktif',
    notes: 'Lisensi Premier (up to 100 Accounts) untuk web server internal.',
  },
  {
    id: '19',
    name: 'Sertifikasi Cisco CCNA - Surya',
    category: 'Sertifikasi Profesi',
    licenseNumber: 'CSCO-11223344',
    owner: 'Surya Pratama - Divisi IT',
    vendor: 'Cisco Systems',
    issueDate: '2022-12-10',
    expiryDate: '2025-12-10',
    status: 'Kadaluarsa',
    notes: 'Sertifikasi CCNA sudah expired.',
  },
  {
    id: '20',
    name: 'Izin Penyelenggaraan Sistem Elektronik (PSE)',
    category: 'Izin Usaha & Legalitas',
    licenseNumber: 'PSE-KOMINFO-2023-010',
    owner: 'Divisi Legal',
    vendor: 'Kementerian Kominfo',
    issueDate: '2023-05-18',
    expiryDate: '2028-05-18',
    status: 'Aktif',
    notes: 'Tanda Daftar Penyelenggara Sistem Elektronik (TDPSE) untuk layanan digital perusahaan.',
  },
];

export const categories: LicenseCategory[] = [
  'Software',
  'Izin Usaha & Legalitas',
  'Sertifikasi Profesi',
];

export const statuses: LicenseStatus[] = [
  'Aktif',
  'Akan Kadaluarsa',
  'Kadaluarsa',
  'Non-aktif',
];
